/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as RegisterProprietorRouteImport } from './routes/register.proprietor'
import { Route as RegisterManagerRouteImport } from './routes/register.manager'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard.vehicles'
import { Route as DashboardBookRouteImport } from './routes/dashboard.book'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const RegisterProprietorRoute = RegisterProprietorRouteImport.update({
  id: '/register/proprietor',
  path: '/register/proprietor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterManagerRoute = RegisterManagerRouteImport.update({
  id: '/register/manager',
  path: '/register/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookRoute = DashboardBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/register/manager': typeof RegisterManagerRoute
  '/register/proprietor': typeof RegisterProprietorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/register/manager': typeof RegisterManagerRoute
  '/register/proprietor': typeof RegisterProprietorRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/register/manager': typeof RegisterManagerRoute
  '/register/proprietor': typeof RegisterProprietorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/book'
    | '/dashboard/vehicles'
    | '/register/manager'
    | '/register/proprietor'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/book'
    | '/dashboard/vehicles'
    | '/register/manager'
    | '/register/proprietor'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/book'
    | '/dashboard/vehicles'
    | '/register/manager'
    | '/register/proprietor'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RegisterManagerRoute: typeof RegisterManagerRoute
  RegisterProprietorRoute: typeof RegisterProprietorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/register/proprietor': {
      id: '/register/proprietor'
      path: '/register/proprietor'
      fullPath: '/register/proprietor'
      preLoaderRoute: typeof RegisterProprietorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/manager': {
      id: '/register/manager'
      path: '/register/manager'
      fullPath: '/register/manager'
      preLoaderRoute: typeof RegisterManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/book': {
      id: '/dashboard/book'
      path: '/book'
      fullPath: '/dashboard/book'
      preLoaderRoute: typeof DashboardBookRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBookRoute: typeof DashboardBookRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookRoute: DashboardBookRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RegisterManagerRoute: RegisterManagerRoute,
  RegisterProprietorRoute: RegisterProprietorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
